Fix problems in scene editor and hierarchy g UI
kablouser/PlatinumEngine pull request #25
Opened 2022-03-29 18:42 UTC by Erdios

❗❗Merge [Inspector Window to actually add/remove/update components of a game object branch](https://github.com/kablouser/PlatinumEngine/pull/24) before merging this branch.

2022-03-29 20:44 UTC, Matt-Cumber requested changes
I've tried to ignore changes from the other PR and the loader changes (I'm not sure why they are here these should be in main already , but will hopefully be resolved by merging main into this branch). 

Code works well, and nice comments make it as easy to follow as it can be. Just need to tidy up the code a little :)

2022-03-29 20:44 UTC, Matt-Cumber commented on Include/SceneManager/HierarchyWindow.h
> +
```suggestion
```

2022-03-29 20:44 UTC, Matt-Cumber commented on Include/SceneManager/HierarchyWindow.h
> +
```suggestion
```

2022-03-29 20:44 UTC, Matt-Cumber commented on Include/SceneManager/HierarchyWindow.h
> +
```suggestion
```

2022-03-29 20:44 UTC, Matt-Cumber commented on Include/SceneManager/Scene.h
> +
```suggestion
```

2022-03-29 20:44 UTC, Matt-Cumber commented on Include/SceneManager/Scene.h
> +
```suggestion
```

2022-03-29 20:44 UTC, Matt-Cumber commented on Source/ComponentComposition/RenderComponent.cpp
> +		//LoadMesh("D:/Download/fourCubes.obj");
```suggestion
```

2022-03-29 20:44 UTC, Matt-Cumber commented on Source/SceneManager/HierarchyWindow.cpp
> +				std::cout<<"test"<<std::endl;
```suggestion
```

2022-03-29 20:44 UTC, Matt-Cumber commented on Source/main.cpp
> +		//Mesh mesh(vertices, indices);
```suggestion
```

2022-03-29 20:44 UTC, Matt-Cumber commented on Source/SceneManager/Scene.cpp
> +			std::rotate(targetGameObjectIterator, movedGameObjectIterator, movedGameObjectIterator+1);
Would you be able to indent these

2022-03-30 13:49 UTC, ShawnWicky commented on Source/SceneEditor/SceneEditor.cpp
> +			_scene->Render(*_renderer);
```suggestion
                        // Update rendering information to renderer
                        _scene->Render(*_renderer);
			_renderer->SetModelMatrix();
			_renderer->SetViewMatrix(_camera.viewMatrix4);
			_renderer->SetProjectionMatrix(_camera.projectionMatrix4);
			_renderer->SetLightProperties();
```

2022-03-31 11:44 UTC, merged