Choose mesh button implement
kablouser/PlatinumEngine pull request #35
Opened 2022-04-05 17:29 UTC by ShawnWicky

check the choose mesh button is work or not
If you would like to check my code. You can check them all :)

2022-04-05 22:02 UTC, kablouser requested changes

2022-04-05 22:02 UTC, kablouser commented on Source/Inspector/InspectorWindow.cpp
> +		if(bool isOpen = _assetHelper->ShowGuiWindow(); _assetHelper->GetMesh() != nullptr&&isOpen == true)
_assetHelper->GetMesh() != nullptr is probably not a good idea.
You can't set the mesh to "none".

2022-04-06 08:07 UTC, ShawnWicky commented on Include/ComponentComposition/RenderComponent.h
>  		ShaderInput _shaderInput;
What did you mean?

2022-04-06 19:09 UTC, kablouser commented on Include/ComponentComposition/RenderComponent.h
>  		ShaderInput _shaderInput;
Each 1 Mesh should have 1 ShaderInput.

2022-04-06 19:53 UTC, closed without merging